stages:
    - build
    - test
    - release
    - deploy

variables:
    TAG_LATEST_PROXY: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME/proxy:latest
    TAG_COMMIT_PROXY: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME/proxy:$CI_COMMIT_SHORT_SHA 

build-job:
    stage: build
    script:
        - echo "Hello, $GITLAB_USER_LOGIN!"

test-job1:
    stage: test
    script:
        - echo "This job tests something"

test-job2:
    stage: test
    script:
        - echo "This job tests something, but takes more time than test-job1."
        - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
        - echo "which simulates a test that runs 20 seconds longer than test-job1"

release:
    image: docker:latest
    stage: release
    services:
        - docker:dind
    script:
        - docker build -t $TAG_COMMIT_PROXY -t $TAG_LATEST_PROXY ./proxy
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker push $TAG_COMMIT_PROXY
        - docker push $TAG_LATEST_PROXY
        

deploy:
    image: ubuntu:latest
    stage: deploy
    tags:
        - deployment
    script:
        - chmod og= $ID_RSA
        - apt update && apt install openssh-client
        - scp -i $ID_RSA -o StrictHostKeyChecking=no docker-compose.yml $SERVER_USER@$SERVER_IP:/srv/portfolio/
        - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd /srv/portfolio"
        - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
        - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker-compose up --build -d"
    environment:
        name: production
        url: http://161.35.167.110
    only:
        - master