version: "3.8"

services:
    
    proxy:
        image: registry.gitlab.com/hitchhiker90/portfolio/master/proxy
        build: ./proxy/
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        ports:
            - "80:80"
            - "443:443"
        networks:
            - site_net
            - evac-sim_net
        depends_on:
            - web
            - evac-sim

    web:
        image: httpd:2.4
        networks:
            - site_net
    
    evac-sim:
        image: registry.gitlab.com/hitchhiker90/evacuation-simulation/main/evac-sim:latest
        build: ../evacuation-simulation/
        networks:
            - evac-sim_net

networks:
    site_net:
        name: site_net
    evac-sim_net:
        name: evac-sim_net
