version: "3.8"

services:
    
    proxy:
        image: registry.gitlab.com/hitchhiker90/portfolio/master/proxy
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        ports:
            - "80:80"
            - "443:443"
        networks:
            - site_net
            - evac-sim_net

    web:
        image: httpd:2.4
        networks:
            - site_net


networks:
    site_net:
    evac-sim_net:
        external: true
